# Generated by Django 4.0.4 on 2022-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=50)),
                ('experience', models.IntegerField()),
                ('previous_company', models.CharField(max_length=60)),
                ('college_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('applied', 'applied'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='applied', max_length=20)),
            ],
        ),
    ]
